version: '3.8'

services:
  train_model:
    build:
      context: .
      dockerfile: Dockerfile.train
    volumes:
      - ./output:/MLDS_Exam/output
    command: python train_classifier.py

  predict_model:
    build:
      context: .
      dockerfile: Dockerfile.predict
    volumes:
      - ./output:/MLDS_Exam/output
    command: python predict_classification.py